[package]
name = "statsd-proxy"
version = "0.1.0"
authors = ["o.ermakov <ermakovolegs@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
